epochs: 20
image_folder: ./crops
batch_size: 128
n_cpu: 12
img_size: 512
checkpoint_interval: 1
checkpoint_dir: checkpoints
use_cuda: true
weighted_sampling: false
expname: general
net: vit  # or (resnet18, resnet50, resnet152, convNext, vit, swin)

